name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

    - name: Set up AVD (Android Virtual Device)
      env:
        AVD_NAME: test
      run: |
        sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;default;x86_64"
        echo "no" | sudo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n $AVD_NAME -k "system-images;android-30;default;x86_64" --device "pixel"
        $ANDROID_SDK_ROOT/emulator/emulator -avd $AVD_NAME -no-window -no-audio -no-boot-anim -gpu off -writable-system -no-snapshot > /dev/null 2>&1 &

    - name: Wait for Emulator to start
      run: |
        adb wait-for-device
        adb shell input keyevent 82

    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest --no-daemon

    - name: Stop Emulator
      run: adb -s emulator-5554 emu kill
