name: Android CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      -master
      -Raneem
      -rahaf
      -aseel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run Unit Tests
      run: ./gradlew test --no-daemon

    - name: Run Lint Checks
      run: ./gradlew lint

    - name: Run UI tests
      run: ./gradlew connectedAndroidTest

    # - name: Run Checkstyle (Java)
    #   run: ./gradlew checkstyle

    # - name: Run PMD (Java)
    #   run: ./gradlew pmd

    # - name: Run OWASP Dependency-Check
    #   run: ./gradlew dependencyCheckAnalyze

    # - name: Run E2E Tests
    #   run: ./gradlew connectedAndroidTest --no-daemon

    # - name: Run Integration Tests
    #   run: ./gradlew integrationTest
